### PR TITLE
Remove validator overwrite

### PR DESCRIPTION
**Pull request by aedart**
This PR extracts validation logic out of the custom validation and into its own class, which is then installed as a validation extension, via the service provider.

The custom validator has now been _marked as deprecated_, because it is really not needed. The validation rule is sufficient.
Lastly, the unit tests have also been adapted to no longer rely on the custom validator instance.

### Related

- #40 
- #44 

### Additional Context

Recently I found myself in a bad situation - I needed to overwrite my application's Validator instance to manually fix an issue. To my great surprise, I found that this package already had overwritten the validator and caused me some frustration (_I was not aware of this behaviour_).
In any case, I thought that I would take a look at how your package could be improved, to avoid the above mentioned situation.

### CODE REVIEW

**Comment by aedart** [comment]
Note: I'm not sure what/why code-coverage is failing. @sunspikes, if you approve of the changes, can you please take over the PR and fix eventual coverage related issues?

**Comment by aedart** [comment]
To anyone that might come across this PR. Due to lack of activity from the author, I was forced to create an [alternative](https://aedart.github.io/athenaeum/archive/current/antivirus/). I hold no ill intention towards the author and hope that he may become active again in the future.

**Comment by KristianI** [comment]
Voting for this PR to be merged 👍🏼 cc @sunspikes

**Comment by bradietilley** [comment]
Should this package be archived or should this PR be merged? 👀

**Comment by aedart** [comment]
@bradietilley I can see that the author has recently been active on this package - he added support for Laravel v11 (_at least in the composer file_). But I cannot say why this PR has not received any attention.

**Comment by sunspikes** [comment]
Thank you @aedart and sorry for the late merge

**Pull request merged**
